[profile.default]
src = "src"
out = "out"
test = "test"
solc = "0.8.23"
evm_version = "paris"

libs = [ "./lib" ]

via_ir = true
optimizer = true
optimizer_runs = 100000000

bytecode_hash = "none"
cbor_metadata = false