name: test

on:
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ir

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "nightly-62def0d68897aae7c2172eabed8085f631625003"

      - name: Install dependencies
        run: forge install

      - name: Run Forge build
        run: |
          forge --version
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          NODE_PROVIDER_BYPASS_KEY: ${{ secrets.NODE_PROVIDER_BYPASS_KEY }}
